# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-15 17:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('content', models.TextField()),
                ('raised_by', models.CharField(max_length=64)),
                ('resolved', models.BooleanField(default=False)),
                ('resolve_comment', models.TextField(default='')),
            ],
        ),
    ]
