# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-16 14:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entry',
            options={'verbose_name_plural': 'entries'},
        ),
        migrations.AlterField(
            model_name='entry',
            name='resolve_comment',
            field=models.TextField(blank=True, default=''),
        ),
    ]
