# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-05 14:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='resolved',
            field=models.BooleanField(default=False),
        ),
    ]
