# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-13 12:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_forbiddenuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='accepted_agbs',
            field=models.BooleanField(default=False),
        ),
    ]
