# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-18 13:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0003_account_type'),
        ('profiles', '0006_auto_20160513_1315'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='points',
        ),
        migrations.AddField(
            model_name='profile',
            name='account',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='ledger.Account'),
            preserve_default=False,
        ),
    ]
