# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-18 13:20
from __future__ import unicode_literals

import bets.util
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Credit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Debit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='account',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='id',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='name',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='type',
        ),
        migrations.AddField(
            model_name='account',
            name='balance',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='transaction',
            name='transaction_id',
            field=models.PositiveIntegerField(default=bets.util.pkgen, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='debit',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ledger.Account'),
        ),
        migrations.AddField(
            model_name='debit',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ledger.Transaction'),
        ),
        migrations.AddField(
            model_name='credit',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ledger.Account'),
        ),
        migrations.AddField(
            model_name='credit',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ledger.Transaction'),
        ),
    ]
