# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-18 13:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0002_auto_20160518_1320'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='type',
            field=models.CharField(choices=[('p', 'Person'), ('b', 'Bet'), ('o', 'Other')], default='o', max_length=1),
            preserve_default=False,
        ),
    ]
