# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-06 09:42
from __future__ import unicode_literals

import bets.util
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ledger', '__first__'),
        ('profiles', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=64)),
                ('picks', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ChoiceBet',
            fields=[
                ('prim_key', models.PositiveIntegerField(default=bets.util.key_gen, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('description', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('pub_date', models.DateField(auto_now_add=True)),
                ('end_bets_date', models.DateField(blank=True, null=True)),
                ('resolved', models.BooleanField(default=False)),
                ('pot', models.PositiveIntegerField(default=0)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ledger.Account')),
                ('forbidden', models.ManyToManyField(blank=True, to='profiles.ForbiddenUser')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.Profile')),
                ('winning_choice', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bets.Choice')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DateBet',
            fields=[
                ('prim_key', models.PositiveIntegerField(default=bets.util.key_gen, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('description', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('pub_date', models.DateField(auto_now_add=True)),
                ('end_bets_date', models.DateField(blank=True, null=True)),
                ('resolved', models.BooleanField(default=False)),
                ('pot', models.PositiveIntegerField(default=0)),
                ('time_period_start', models.DateField(blank=True, null=True)),
                ('time_period_end', models.DateField(blank=True, null=True)),
                ('winning_date', models.DateField(blank=True, null=True)),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ledger.Account')),
                ('forbidden', models.ManyToManyField(blank=True, to='profiles.ForbiddenUser')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.Profile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PlacedChoiceBet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('placed', models.PositiveIntegerField()),
                ('chosen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bets.Choice')),
                ('placed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.Profile')),
                ('placed_on', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bets.ChoiceBet')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ledger.Transaction')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PlacedDateBet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('placed', models.PositiveIntegerField()),
                ('placed_date', models.DateField()),
                ('placed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.Profile')),
                ('placed_on', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bets.DateBet')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ledger.Transaction')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='choice',
            name='belongs_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bets.ChoiceBet'),
        ),
    ]
