# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-27 19:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='picks',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='choicebet',
            name='pub_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='datebet',
            name='pub_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
