# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-02 16:04
from __future__ import unicode_literals

import bets.util
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_forbiddenuser'),
        ('bets', '0002_auto_20160429_1007'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bet',
            fields=[
                ('prim_key', models.PositiveIntegerField(default=bets.util.pkgen, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('description', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('pub_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('resolved', models.BooleanField(default=False)),
                ('type', models.CharField(choices=[('choice', 'Choices')], max_length=64)),
                ('forbidden', models.ManyToManyField(to='profiles.ForbiddenUser')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=64)),
                ('belongs_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bets.Bet')),
            ],
        ),
        migrations.CreateModel(
            name='ChoiceBet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placed', models.PositiveIntegerField()),
                ('chosen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bets.Choice')),
                ('placed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.Profile')),
                ('placed_on', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bets.Bet')),
            ],
        ),
        migrations.RemoveField(
            model_name='binarybet',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='placedbinarybet',
            name='placed_by',
        ),
        migrations.RemoveField(
            model_name='placedbinarybet',
            name='placed_on',
        ),
        migrations.DeleteModel(
            name='BinaryBet',
        ),
        migrations.DeleteModel(
            name='PlacedBinaryBet',
        ),
    ]
