# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-01 13:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bets', '0002_auto_20160527_1913'),
    ]

    operations = [
        migrations.AddField(
            model_name='choicebet',
            name='winning_choice',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bets.Choice'),
        ),
    ]
