# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-01 14:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bets', '0003_choicebet_winning_choice'),
    ]

    operations = [
        migrations.AddField(
            model_name='datebet',
            name='winning_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
