# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-13 11:34
from __future__ import unicode_literals

import bets.util
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_forbiddenuser'),
        ('bets', '0003_auto_20160502_1604'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChoiceB',
            fields=[
                ('prim_key', models.PositiveIntegerField(default=bets.util.pkgen, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('description', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('pub_date', models.DateField()),
                ('end_bets', models.DateField(blank=True, null=True)),
                ('resolved', models.BooleanField(default=False)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('forbidden', models.ManyToManyField(to='profiles.ForbiddenUser')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.Profile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RenameModel(
            old_name='ChoiceBet',
            new_name='PlacedChoiceBet',
        ),
        migrations.RemoveField(
            model_name='bet',
            name='forbidden',
        ),
        migrations.RemoveField(
            model_name='bet',
            name='owner',
        ),
        migrations.AlterField(
            model_name='choice',
            name='belongs_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bets.ChoiceB'),
        ),
        migrations.AlterField(
            model_name='placedchoicebet',
            name='placed_on',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bets.ChoiceB'),
        ),
        migrations.DeleteModel(
            name='Bet',
        ),
    ]
