# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-13 11:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bets', '0004_auto_20160513_1134'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ChoiceB',
            new_name='ChoiceBet',
        ),
    ]
