# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-13 12:24
from __future__ import unicode_literals

import bets.util
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_forbiddenuser'),
        ('bets', '0005_auto_20160513_1136'),
    ]

    operations = [
        migrations.CreateModel(
            name='DateBet',
            fields=[
                ('prim_key', models.PositiveIntegerField(default=bets.util.pkgen, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('description', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('pub_date', models.DateField()),
                ('end_bets', models.DateField(blank=True, null=True)),
                ('resolved', models.BooleanField(default=False)),
                ('foobar', models.CharField(default='foobar', max_length=6)),
                ('forbidden', models.ManyToManyField(to='profiles.ForbiddenUser')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.Profile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PlacedDateBet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placed', models.PositiveIntegerField()),
                ('placed_date', models.DateField()),
                ('placed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.Profile')),
                ('placed_on', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bets.DateBet')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
