# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-13 12:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bets', '0006_datebet_placeddatebet'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choicebet',
            old_name='end_bets',
            new_name='end_bets_date',
        ),
        migrations.RenameField(
            model_name='datebet',
            old_name='end_bets',
            new_name='end_bets_date',
        ),
    ]
