# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-13 14:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bets', '0007_auto_20160513_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choicebet',
            name='forbidden',
            field=models.ManyToManyField(blank=True, to='profiles.ForbiddenUser'),
        ),
        migrations.AlterField(
            model_name='datebet',
            name='forbidden',
            field=models.ManyToManyField(blank=True, to='profiles.ForbiddenUser'),
        ),
    ]
