# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-13 14:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bets', '0008_auto_20160513_1415'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datebet',
            name='foobar',
        ),
        migrations.AddField(
            model_name='datebet',
            name='time_period_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datebet',
            name='time_period_start',
            field=models.DateField(blank=True, null=True),
        ),
    ]
