# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-16 14:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bets', '0009_auto_20160513_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choicebet',
            name='pub_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='datebet',
            name='pub_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
