# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-17 17:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bets', '0010_auto_20160516_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choicebet',
            name='pub_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='datebet',
            name='pub_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
