# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-17 18:28
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('bets', '0011_auto_20160517_1747'),
    ]

    operations = [
        migrations.AddField(
            model_name='placedchoicebet',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 5, 17, 18, 28, 16, 923813, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='placeddatebet',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 5, 17, 18, 28, 27, 704176, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
