# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-18 13:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bets', '0012_auto_20160517_1828'),
    ]

    operations = [
        migrations.AddField(
            model_name='choicebet',
            name='pot',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='datebet',
            name='pot',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
