# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-18 13:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0003_account_type'),
        ('bets', '0013_auto_20160518_1306'),
    ]

    operations = [
        migrations.AddField(
            model_name='choicebet',
            name='account',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='ledger.Account'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='datebet',
            name='account',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='ledger.Account'),
            preserve_default=False,
        ),
    ]
